// File: dff.v
// Generated by MyHDL 0.8
// Date: Tue Sep  2 11:35:59 2014


`timescale 1ns/10ps

module dff (
    resetn,
    en,
    q,
    d,
    clk
);


input resetn;
input en;
output q;
reg q;
input d;
input clk;






always @(posedge clk) begin: DFF_LOGIC
    if (resetn == 0) begin
        q <= 0;
    end
    else begin
        if (en) begin
            q <= d;
        end
    end
end

endmodule
